using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//https://www.goodway.com.br/distancias.htm
namespace FSI_estrategias_de_buscas
{
    public class Capitais
    {
        public Dictionary<string, Dictionary<string, int>> DistanciasTerrestres { get; private set; }
        public Dictionary<string, Dictionary<string, int>> DistanciasAereas { get; private set; }

        public Capitais()
        {
            DistanciasTerrestres = new Dictionary<string, Dictionary<string, int>>
            {
                ["Aracaju"] = new Dictionary<string, int>
                {
                    ["Belém"] = 2079,
                    ["Belo Horizonte"] = 1578,
                    ["Boa Vista"] = 6000,
                    ["Brasília"] = 1652,
                    ["Campo Grande"] = 2765,
                    ["Cuiabá"] = 2775,
                    ["Curitiba"] = 2595,
                    ["Florianópolis"] = 2892,
                    ["Fortaleza"] = 1183,
                    ["Goiania"] = 1848,
                    ["João Pessoa"] = 611,
                    ["Macapá"] = 0,
                    ["Maceió"] = 294,
                    ["Manaus"] = 5215,
                    ["Natal"] = 788,
                    ["Palmas"] = 1662,
                    ["Porto Alegre"] = 3296,
                    ["Porto Velho"] = 4230,
                    ["Recife"] = 501,
                    ["Rio Branco"] = 4763,
                    ["Rio de Janeiro"] = 1855,
                    ["Salvador"] = 356,
                    ["São Luis"] = 1578,
                    ["São Paulo"] = 2187,
                    ["Teresina"] = 1142,
                    ["Vitória"] = 1408
                },
                ["Belém"] = new Dictionary<string, int>
                {
                    ["Belo Horizonte"] = 2824,
                    ["Boa Vista"] = 6083,
                    ["Brasília"] = 2120,
                    ["Campo Grande"] = 2942,
                    ["Cuiabá"] = 2941,
                    ["Curitiba"] = 3193,
                    ["Florianópolis"] = 3500,
                    ["Fortaleza"] = 1610,
                    ["Goiania"] = 2017,
                    ["João Pessoa"] = 2161,
                    ["Macapá"] = 0,
                    ["Maceió"] = 2173,
                    ["Manaus"] = 5298,
                    ["Natal"] = 2108,
                    ["Palmas"] = 1283,
                    ["Porto Alegre"] = 3852,
                    ["Porto Velho"] = 4397,
                    ["Recife"] = 2074,
                    ["Rio Branco"] = 4931,
                    ["Rio de Janeiro"] = 3250,
                    ["Salvador"] = 2100,
                    ["São Luis"] = 806,
                    ["São Paulo"] = 2933,
                    ["Teresina"] = 947,
                    ["Vitória"] = 3108
                },
                ["Belo Horizonte"] = new Dictionary<string, int>
                {
                    ["Boa Vista"] = 4736,
                    ["Brasília"] = 716,
                    ["Campo Grande"] = 1454,
                    ["Cuiabá"] = 1594,
                    ["Curitiba"] = 1004,
                    ["Florianópolis"] = 1301,
                    ["Fortaleza"] = 2528,
                    ["Goiania"] = 906,
                    ["João Pessoa"] = 2171,
                    ["Macapá"] = 0,
                    ["Maceió"] = 1854,
                    ["Manaus"] = 3951,
                    ["Natal"] = 2348,
                    ["Palmas"] = 1690,
                    ["Porto Alegre"] = 1712,
                    ["Porto Velho"] = 3050,
                    ["Recife"] = 2061,
                    ["Rio Branco"] = 3584,
                    ["Rio de Janeiro"] = 434,
                    ["Salvador"] = 1372,
                    ["São Luis"] = 2738,
                    ["São Paulo"] = 586,
                    ["Teresina"] = 2302,
                    ["Vitória"] = 524
                },
                ["Boa Vista"] = new Dictionary<string, int>
                {
                    ["Brasília"] = 4275,
                    ["Campo Grande"] = 3836,
                    ["Cuiabá"] = 3142,
                    ["Curitiba"] = 4821,
                    ["Florianópolis"] = 5128,
                    ["Fortaleza"] = 6548,
                    ["Goiania"] = 4076,
                    ["João Pessoa"] = 6593,
                    ["Macapá"] = 0,
                    ["Maceió"] = 6279,
                    ["Manaus"] = 785,
                    ["Natal"] = 6770,
                    ["Palmas"] = 4926,
                    ["Porto Alegre"] = 5348,
                    ["Porto Velho"] = 1686,
                    ["Recife"] = 6483,
                    ["Rio Branco"] = 2230,
                    ["Rio de Janeiro"] = 5159,
                    ["Salvador"] = 5794,
                    ["São Luis"] = 6120,
                    ["São Paulo"] = 4756,
                    ["Teresina"] = 6052,
                    ["Vitória"] = 5261
                },
                ["Brasília"] = new Dictionary<string, int>
                {
                    ["Campo Grande"] = 1134,
                    ["Cuiabá"] = 1133,
                    ["Curitiba"] = 1366,
                    ["Florianópolis"] = 1673,
                    ["Fortaleza"] = 2200,
                    ["Goiania"] = 209,
                    ["João Pessoa"] = 2245,
                    ["Macapá"] = 0,
                    ["Maceió"] = 1930,
                    ["Manaus"] = 3490,
                    ["Natal"] = 2422,
                    ["Palmas"] = 973,
                    ["Porto Alegre"] = 2027,
                    ["Porto Velho"] = 2589,
                    ["Recife"] = 2135,
                    ["Rio Branco"] = 3123,
                    ["Rio de Janeiro"] = 1148,
                    ["Salvador"] = 1446,
                    ["São Luis"] = 2157,
                    ["São Paulo"] = 1015,
                    ["Teresina"] = 1789,
                    ["Vitória"] = 1239
                },
                ["Campo Grande"] = new Dictionary<string, int>
                {
                    ["Cuiabá"] = 694,
                    ["Curitiba"] = 991,
                    ["Florianópolis"] = 1298,
                    ["Fortaleza"] = 3407,
                    ["Goiania"] = 935,
                    ["João Pessoa"] = 3357,
                    ["Macapá"] = 0,
                    ["Maceió"] = 3040,
                    ["Manaus"] = 3051,
                    ["Natal"] = 3534,
                    ["Palmas"] = 1785,
                    ["Porto Alegre"] = 1518,
                    ["Porto Velho"] = 2150,
                    ["Recife"] = 3247,
                    ["Rio Branco"] = 2684,
                    ["Rio de Janeiro"] = 1444,
                    ["Salvador"] = 2568,
                    ["São Luis"] = 2979,
                    ["São Paulo"] = 1014,
                    ["Teresina"] = 2911,
                    ["Vitória"] = 1892
                },
                ["Cuiabá"] = new Dictionary<string, int>
                {
                    ["Curitiba"] = 1679,
                    ["Florianópolis"] = 1986,
                    ["Fortaleza"] = 3406,
                    ["Goiania"] = 934,
                    ["João Pessoa"] = 3366,
                    ["Macapá"] = 0,
                    ["Maceió"] = 3049,
                    ["Manaus"] = 2357,
                    ["Natal"] = 3543,
                    ["Palmas"] = 1784,
                    ["Porto Alegre"] = 2206,
                    ["Porto Velho"] = 1456,
                    ["Recife"] = 3255,
                    ["Rio Branco"] = 1990,
                    ["Rio de Janeiro"] = 2017,
                    ["Salvador"] = 2566,
                    ["São Luis"] = 2978,
                    ["São Paulo"] = 1614,
                    ["Teresina"] = 2910,
                    ["Vitória"] = 2119
                },
                ["Curitiba"] = new Dictionary<string, int>
                {
                    ["Florianópolis"] = 300,
                    ["Fortaleza"] = 3541,
                    ["Goiania"] = 1186,
                    ["João Pessoa"] = 3188,
                    ["Macapá"] = 0,
                    ["Maceió"] = 2871,
                    ["Manaus"] = 4036,
                    ["Natal"] = 3365,
                    ["Palmas"] = 2036,
                    ["Porto Alegre"] = 711,
                    ["Porto Velho"] = 3135,
                    ["Recife"] = 3078,
                    ["Rio Branco"] = 3669,
                    ["Rio de Janeiro"] = 852,
                    ["Salvador"] = 2385,
                    ["São Luis"] = 3230,
                    ["São Paulo"] = 408,
                    ["Teresina"] = 3143,
                    ["Vitória"] = 1300
                },
                ["Florianópolis"] = new Dictionary<string, int>
                {
                    ["Fortaleza"] = 3838,
                    ["Goiania"] = 1493,
                    ["João Pessoa"] = 3485,
                    ["Macapá"] = 0,
                    ["Maceió"] = 3168,
                    ["Manaus"] = 4443,
                    ["Natal"] = 3662,
                    ["Palmas"] = 2336,
                    ["Porto Alegre"] = 476,
                    ["Porto Velho"] = 3442,
                    ["Recife"] = 3375,
                    ["Rio Branco"] = 3976,
                    ["Rio de Janeiro"] = 1144,
                    ["Salvador"] = 2682,
                    ["São Luis"] = 3537,
                    ["São Paulo"] = 705,
                    ["Teresina"] = 3450,
                    ["Vitória"] = 1597
                },
                ["Fortaleza"] = new Dictionary<string, int>
                {
                    ["Goiania"] = 2482,
                    ["João Pessoa"] = 688,
                    ["Macapá"] = 0,
                    ["Maceió"] = 1075,
                    ["Manaus"] = 5763,
                    ["Natal"] = 537,
                    ["Palmas"] = 2035,
                    ["Porto Alegre"] = 4242,
                    ["Porto Velho"] = 4862,
                    ["Recife"] = 800,
                    ["Rio Branco"] = 5396,
                    ["Rio de Janeiro"] = 2805,
                    ["Salvador"] = 1389,
                    ["São Luis"] = 1070,
                    ["São Paulo"] = 3127,
                    ["Teresina"] = 634,
                    ["Vitória"] = 2397
                },
                ["Goiania"] = new Dictionary<string, int>
                {
                    ["João Pessoa"] = 2442,
                    ["Macapá"] = 0,
                    ["Maceió"] = 2125,
                    ["Manaus"] = 3291,
                    ["Natal"] = 2618,
                    ["Palmas"] = 874,
                    ["Porto Alegre"] = 1847,
                    ["Porto Velho"] = 2390,
                    ["Recife"] = 2332,
                    ["Rio Branco"] = 2924,
                    ["Rio de Janeiro"] = 1338,
                    ["Salvador"] = 1643,
                    ["São Luis"] = 2054,
                    ["São Paulo"] = 926,
                    ["Teresina"] = 1986,
                    ["Vitória"] = 1428
                },
                ["João Pessoa"] = new Dictionary<string, int>
                {
                    ["Macapá"] = 0,
                    ["Maceió"] = 395,
                    ["Manaus"] = 5803,
                    ["Natal"] = 185,
                    ["Palmas"] = 2253,
                    ["Porto Alegre"] = 3889,
                    ["Porto Velho"] = 4822,
                    ["Recife"] = 120,
                    ["Rio Branco"] = 5356,
                    ["Rio de Janeiro"] = 2448,
                    ["Salvador"] = 949,
                    ["São Luis"] = 1660,
                    ["São Paulo"] = 2770,
                    ["Teresina"] = 1224,
                    ["Vitória"] = 2001
                },
                ["Maceió"] = new Dictionary<string, int>
                {
                    ["Manaus"] = 5491,
                    ["Natal"] = 572,
                    ["Palmas"] = 1851,
                    ["Porto Alegre"] = 3572,
                    ["Porto Velho"] = 4505,
                    ["Recife"] = 285,
                    ["Rio Branco"] = 5039,
                    ["Rio de Janeiro"] = 2131,
                    ["Salvador"] = 632,
                    ["São Luis"] = 1672,
                    ["São Paulo"] = 2453,
                    ["Teresina"] = 1236,
                    ["Vitória"] = 1684
                },
                ["Manaus"] = new Dictionary<string, int>
                {
                    ["Natal"] = 5985,
                    ["Palmas"] = 4141,
                    ["Porto Alegre"] = 4563,
                    ["Porto Velho"] = 901,
                    ["Recife"] = 5698,
                    ["Rio Branco"] = 1445,
                    ["Rio de Janeiro"] = 4374,
                    ["Salvador"] = 5009,
                    ["São Luis"] = 5335,
                    ["São Paulo"] = 3971,
                    ["Teresina"] = 5267,
                    ["Vitória"] = 4476
                },
                ["Natal"] = new Dictionary<string, int>
                {
                    ["Palmas"] = 2345,
                    ["Porto Alegre"] = 4066,
                    ["Porto Velho"] = 4998,
                    ["Recife"] = 297,
                    ["Rio Branco"] = 5533,
                    ["Rio de Janeiro"] = 2625,
                    ["Salvador"] = 1126,
                    ["São Luis"] = 1607,
                    ["São Paulo"] = 2947,
                    ["Teresina"] = 1171,
                    ["Vitória"] = 2178
                },
                ["Palmas"] = new Dictionary<string, int>
                {
                    ["Porto Alegre"] = 2747,
                    ["Porto Velho"] = 0,
                    ["Recife"] = 2058,
                    ["Rio Branco"] = 3764,
                    ["Rio de Janeiro"] = 2124,
                    ["Salvador"] = 1454,
                    ["São Luis"] = 1386,
                    ["São Paulo"] = 1776,
                    ["Teresina"] = 1401,
                    ["Vitória"] = 2214
                },
                ["Porto Alegre"] = new Dictionary<string, int>
                {
                    ["Porto Velho"] = 3662,
                    ["Recife"] = 3779,
                    ["Rio Branco"] = 4196,
                    ["Rio de Janeiro"] = 1553,
                    ["Salvador"] = 3090,
                    ["São Luis"] = 3891,
                    ["São Paulo"] = 1109,
                    ["Teresina"] = 3804,
                    ["Vitória"] = 2001
                },
                ["Porto Velho"] = new Dictionary<string, int>
                {
                    ["Recife"] = 4712,
                    ["Rio Branco"] = 544,
                    ["Rio de Janeiro"] = 3473,
                    ["Salvador"] = 4023,
                    ["São Luis"] = 4434,
                    ["São Paulo"] = 3070,
                    ["Teresina"] = 4366,
                    ["Vitória"] = 3575
                },
                ["Recife"] = new Dictionary<string, int>
                {
                    ["Rio Branco"] = 5243,
                    ["Rio de Janeiro"] = 2338,
                    ["Salvador"] = 839,
                    ["São Luis"] = 1573,
                    ["São Paulo"] = 2660,
                    ["Teresina"] = 1137,
                    ["Vitória"] = 1831
                },
                ["Rio Branco"] = new Dictionary<string, int>
                {
                    ["Rio de Janeiro"] = 4007,
                    ["Salvador"] = 4457,
                    ["São Luis"] = 4968,
                    ["São Paulo"] = 3604,
                    ["Teresina"] = 4900,
                    ["Vitória"] = 4109
                },
                ["Rio de Janeiro"] = new Dictionary<string, int>
                {
                    ["Salvador"] = 1649,
                    ["São Luis"] = 3015,
                    ["São Paulo"] = 429,
                    ["Teresina"] = 2579,
                    ["Vitória"] = 521
                },
                ["Salvador"] = new Dictionary<string, int>
                {
                    ["São Luis"] = 1599,
                    ["São Paulo"] = 1962,
                    ["Teresina"] = 1163,
                    ["Vitória"] = 1202
                },
                ["São Luis"] = new Dictionary<string, int>
                {
                    ["São Paulo"] = 2970,
                    ["Teresina"] = 446,
                    ["Vitória"] = 2607
                },
                ["São Paulo"] = new Dictionary<string, int>
                {
                    ["Teresina"] = 2792,
                    ["Vitória"] = 882
                },
                ["Teresina"] = new Dictionary<string, int>
                {
                    ["Vitória"] = 2171
                }
            };

            DistanciasAereas = new Dictionary<string, Dictionary<string, int>>
            {
                ["Aracaju"] = new Dictionary<string, int>
                {
                    ["Belém"] = 1641,
                    ["Belo Horizonte"] = 1248,
                    ["Boa Vista"] = 3022,
                    ["Brasília"] = 1292,
                    ["Campo Grande"] = 2155,
                    ["Cuiabá"] = 2121,
                    ["Curitiba"] = 2061,
                    ["Florianópolis"] = 2207,
                    ["Fortaleza"] = 815,
                    ["Goiania"] = 1461,
                    ["João Pessoa"] = 486,
                    ["Macapá"] = 1967,
                    ["Maceió"] = 201,
                    ["Manaus"] = 2673,
                    ["Natal"] = 604,
                    ["Palmas"] = 1235,
                    ["Porto Alegre"] = 2580,
                    ["Porto Velho"] = 2946,
                    ["Recife"] = 398,
                    ["Rio Branco"] = 3359,
                    ["Rio de Janeiro"] = 1482,
                    ["Salvador"] = 277,
                    ["São Luis"] = 1226,
                    ["São Paulo"] = 1731,
                    ["Teresina"] = 903,
                    ["Vitória"] = 1102
                },
                ["Belém"] = new Dictionary<string, int>
                {
                    ["Belo Horizonte"] = 2111,
                    ["Boa Vista"] = 1432,
                    ["Brasília"] = 1592,
                    ["Campo Grande"] = 2212,
                    ["Cuiabá"] = 1778,
                    ["Curitiba"] = 2665,
                    ["Florianópolis"] = 2904,
                    ["Fortaleza"] = 1133,
                    ["Goiania"] = 1693,
                    ["João Pessoa"] = 1636,
                    ["Macapá"] = 329,
                    ["Maceió"] = 1680,
                    ["Manaus"] = 1292,
                    ["Natal"] = 1550,
                    ["Palmas"] = 973,
                    ["Porto Alegre"] = 3180,
                    ["Porto Velho"] = 1886,
                    ["Recife"] = 1676,
                    ["Rio Branco"] = 2333,
                    ["Rio de Janeiro"] = 2450,
                    ["Salvador"] = 1687,
                    ["São Luis"] = 481,
                    ["São Paulo"] = 2463,
                    ["Teresina"] = 750,
                    ["Vitória"] = 2275
                },
                ["Belo Horizonte"] = new Dictionary<string, int>
                {
                    ["Belém"] = 21111,
                    ["Boa Vista"] = 3117,
                    ["Brasília"] = 624,
                    ["Campo Grande"] = 1118,
                    ["Cuiabá"] = 1372,
                    ["Curitiba"] = 820,
                    ["Florianópolis"] = 973,
                    ["Fortaleza"] = 1893,
                    ["Goiania"] = 666,
                    ["João Pessoa"] = 1726,
                    ["Macapá"] = 2349,
                    ["Maceió"] = 1439,
                    ["Manaus"] = 2556,
                    ["Natal"] = 1831,
                    ["Palmas"] = 1178,
                    ["Porto Alegre"] = 1341,
                    ["Porto Velho"] = 2477,
                    ["Recife"] = 1639,
                    ["Rio Branco"] = 2786,
                    ["Rio de Janeiro"] = 339,
                    ["Salvador"] = 964,
                    ["São Luis"] = 1932,
                    ["São Paulo"] = 489,
                    ["Teresina"] = 1652,
                    ["Vitória"] = 378
                },
                ["Boa Vista"] = new Dictionary<string, int>
                {
                    ["Brasília"] = 2496,
                    ["Campo Grande"] = 2667,
                    ["Cuiabá"] = 2107,
                    ["Curitiba"] = 3370,
                    ["Florianópolis"] = 3620,
                    ["Fortaleza"] = 2562,
                    ["Goiania"] = 2503,
                    ["João Pessoa"] = 3067,
                    ["Macapá"] = 1110,
                    ["Maceió"] = 3089,
                    ["Manaus"] = 661,
                    ["Natal"] = 2983,
                    ["Palmas"] = 1988,
                    ["Porto Alegre"] = 3785,
                    ["Porto Velho"] = 1335,
                    ["Recife"] = 3103,
                    ["Rio Branco"] = 1626,
                    ["Rio de Janeiro"] = 3128,
                    ["Salvador"] = 3009,
                    ["São Luis"] = 1913,
                    ["São Paulo"] = 3300,
                    ["Teresina"] = 2169,
                    ["Vitória"] = 3394
                },
                ["Brasília"] = new Dictionary<string, int>
                {
                    ["Campo Grande"] = 878,
                    ["Cuiabá"] = 873,
                    ["Curitiba"] = 1081,
                    ["Florianópolis"] = 1314,
                    ["Fortaleza"] = 1687,
                    ["Goiania"] = 173,
                    ["João Pessoa"] = 1716,
                    ["Macapá"] = 1791,
                    ["Maceió"] = 1485,
                    ["Manaus"] = 1932,
                    ["Natal"] = 1775,
                    ["Palmas"] = 620,
                    ["Porto Alegre"] = 1619,
                    ["Porto Velho"] = 1900,
                    ["Recife"] = 1657,
                    ["Rio Branco"] = 2246,
                    ["Rio de Janeiro"] = 933,
                    ["Salvador"] = 1060,
                    ["São Luis"] = 1524,
                    ["São Paulo"] = 873,
                    ["Teresina"] = 1313,
                    ["Vitória"] = 947
                },
                ["Campo Grande"] = new Dictionary<string, int>
                {
                    ["Cuiabá"] = 559,
                    ["Curitiba"] = 780,
                    ["Florianópolis"] = 1007,
                    ["Fortaleza"] = 2547,
                    ["Goiania"] = 705,
                    ["João Pessoa"] = 2593,
                    ["Macapá"] = 2309,
                    ["Maceió"] = 2352,
                    ["Manaus"] = 2013,
                    ["Natal"] = 2654,
                    ["Palmas"] = 1320,
                    ["Porto Alegre"] = 1119,
                    ["Porto Velho"] = 1634,
                    ["Recife"] = 2530,
                    ["Rio Branco"] = 1827,
                    ["Rio de Janeiro"] = 1212,
                    ["Salvador"] = 1905,
                    ["São Luis"] = 2284,
                    ["São Paulo"] = 894,
                    ["Teresina"] = 2132,
                    ["Vitória"] = 1490
                },
                ["Cuiabá"] = new Dictionary<string, int>
                {
                    ["Curitiba"] = 1302,
                    ["Florianópolis"] = 1543,
                    ["Fortaleza"] = 2329,
                    ["Goiania"] = 740,
                    ["João Pessoa"] = 2495,
                    ["Macapá"] = 1822,
                    ["Maceió"] = 2302,
                    ["Manaus"] = 1453,
                    ["Natal"] = 2524,
                    ["Palmas"] = 1029,
                    ["Porto Alegre"] = 1679,
                    ["Porto Velho"] = 1137,
                    ["Recife"] = 2452,
                    ["Rio Branco"] = 1414,
                    ["Rio de Janeiro"] = 1575,
                    ["Salvador"] = 1915,
                    ["São Luis"] = 1942,
                    ["São Paulo"] = 1326,
                    ["Teresina"] = 1862,
                    ["Vitória"] = 1745
                },
                ["Curitiba"] = new Dictionary<string, int>
                {
                    ["Florianópolis"] = 251,
                    ["Fortaleza"] = 2670,
                    ["Goiania"] = 972,
                    ["João Pessoa"] = 2545,
                    ["Macapá"] = 2836,
                    ["Maceió"] = 2259,
                    ["Manaus"] = 2734,
                    ["Natal"] = 2645,
                    ["Palmas"] = 1693,
                    ["Porto Alegre"] = 546,
                    ["Porto Velho"] = 2412,
                    ["Recife"] = 2459,
                    ["Rio Branco"] = 2601,
                    ["Rio de Janeiro"] = 675,
                    ["Salvador"] = 1784,
                    ["São Luis"] = 2599,
                    ["São Paulo"] = 338,
                    ["Teresina"] = 2362,
                    ["Vitória"] = 1076
                },
                ["Florianópolis"] = new Dictionary<string, int>
                {
                    ["Fortaleza"] = 2857,
                    ["Goiania"] = 1215,
                    ["João Pessoa"] = 2693,
                    ["Macapá"] = 3082,
                    ["Maceió"] = 2402,
                    ["Manaus"] = 2981,
                    ["Natal"] = 2802,
                    ["Palmas"] = 1931,
                    ["Porto Alegre"] = 376,
                    ["Porto Velho"] = 2641,
                    ["Recife"] = 2603,
                    ["Rio Branco"] = 2809,
                    ["Rio de Janeiro"] = 748,
                    ["Salvador"] = 1930,
                    ["São Luis"] = 2821,
                    ["São Paulo"] = 489,
                    ["Teresina"] = 2573,
                    ["Vitória"] = 1160
                },               
                ["Fortaleza"] = new Dictionary<string, int>
                {
                    ["Goiania"] = 1854,
                    ["João Pessoa"] = 555,
                    ["Macapá"] = 1451,
                    ["Maceió"] = 730,
                    ["Manaus"] = 2383,
                    ["Natal"] = 435,
                    ["Palmas"] = 1300,
                    ["Porto Alegre"] = 3213,
                    ["Porto Velho"] = 2855,
                    ["Recife"] = 629,
                    ["Rio Branco"] = 3300,
                    ["Rio de Janeiro"] = 2190,
                    ["Salvador"] = 1028,
                    ["São Luis"] = 652,
                    ["São Paulo"] = 2368,
                    ["Teresina"] = 495,
                    ["Vitória"] = 1855
                },
                ["Goiania"] = new Dictionary<string, int>
                {
                    ["João Pessoa"] = 1889,
                    ["Macapá"] = 1868,
                    ["Maceió"] = 1656,
                    ["Manaus"] = 1912,
                    ["Natal"] = 1948,
                    ["Palmas"] = 724,
                    ["Porto Alegre"] = 1497,
                    ["Porto Velho"] = 1813,
                    ["Recife"] = 1829,
                    ["Rio Branco"] = 2138,
                    ["Rio de Janeiro"] = 936,
                    ["Salvador"] = 1225,
                    ["São Luis"] = 1662,
                    ["São Paulo"] = 810,
                    ["Teresina"] = 1467,
                    ["Vitória"] = 1022
                },
                
            };
        }
    }

}
